#Aplicación
spring.application.name=apibazar
server.port=${PORT:8080}

#DB
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#Manejo de sesión
spring.jpa.open-in-view=false

#Token JWT
security.jwt.secret=${JWT_SECRET}
security.jwt.user.generator=${JWT_USER_GENERATOR}


